########################################################################
# This program is a free software tool, which does ensemble in-network machine learning.
# licensed under Apache-2.0
#
# Copyright (c) 2020-2021 Changgang Zheng
# Copyright (c) Computing Infrastructure Group, Department of Engineering Science, University of Oxford & YINS, Yale University
# E-mail: changgang.zheng@eng.ox.ac.uk (valid until July 2024),
# changgang.zheng@yale.edu (valid until October 2022) or changgangzheng@qq.com (no expiration date)
#########################################################################
# This file was autogenerated

#include <core.p4>
#include <v1model.p4>

/*************************************************************************
***************************** constants **********************************
*************************************************************************/

const bit<16> TYPE_IPV4 = 0x800;
const bit<16> TYPE_DINC = 0x1234;
const bit<8>  DINC_P     = 0x50;   // 'P'
const bit<8>  DINC_4     = 0x34;   // '4'
const bit<8>  DINC_VER   = 0x01;   // v0.1
typedef bit<9> egressSpec_t;
typedef bit<48> macAddr_t;
typedef bit<32> ip4Addr_t;

/*************************************************************************
****************************** headers ***********************************
*************************************************************************/

header ethernet_h {
    macAddr_t dstAddr;
    macAddr_t srcAddr;
    bit<16> etherType;
}

header ipv4_h{
    bit < 4 > version;
    bit < 4 > ihl;
    bit < 8 > diffserv;
    bit < 16 > totalLen;
    bit < 16 > identification;
    bit < 3 > flags;
    bit < 13 > fragOffset;
    bit < 8 > ttl;
    bit < 8 > protocol;
    bit < 16 > hdrChecksum;
    ip4Addr_t srcAddr;
    ip4Addr_t dstAddr;
}

header DINC_h{
    bit<8> p;
    bit<8> four;
    bit<8> ver;
    bit<8> typ;
    bit<32> E_bitmap;
    }

header DINC_meta_h{
    bit<32> storage0;
    bit<32> storage1;
    bit<32> storage2;
    bit<32> storage3;
}

struct header_t {
    ethernet_h   ethernet;
    ipv4_h       ipv4;
    DINC_h       DINC;
    DINC_meta_h  DINC_meta;
}

/*************************************************************************
***************************** metadata **********************************
*************************************************************************/

struct metadata_t {
    bit<1> code_f0;
    bit<2> code_f1;
    bit<32> result;
    bit<3> code_f2;
    bit<3> code_f3;
}

/*************************************************************************
*********************** Ingress Parser ***********************************
*************************************************************************/

parser SwitchParser(
    packet_in pkt,
    out header_t hdr,
    inout metadata_t meta,
    inout standard_metadata_t ig_intr_md) {

    state start {
        transition parse_ethernet;
    }

    state parse_ethernet {
        pkt.extract(hdr.ethernet);
        transition select(hdr.ethernet.etherType) {
            TYPE_DINC         : check_DINC_version;
            TYPE_IPV4         : parse_ipv4;
            default           : accept;
        }
    }

    state parse_ipv4 {
        pkt.extract(hdr.ipv4);
        transition accept;
    }

    state check_DINC_version {
        pkt.extract(hdr.ipv4);
        transition select(pkt.lookahead<DINC_h>().E_bitmap) {
        0b11000000000000000000000000000000: parse_DINC0;
        default                    : accept;
        }
    }

    state parse_DINC0{
        pkt.extract(hdr.DINC_meta);
        meta.code_f0 = hdr.DINC_meta.storage0[0:0];
        meta.code_f1 = hdr.DINC_meta.storage0[2:1];
        meta.code_f2 = hdr.DINC_meta.storage0[5:3];
        meta.code_f3 = hdr.DINC_meta.storage0[8:6];
        transition accept;
    }
}

/*************************************************************************
*********************** Egress Deparser *********************************
**************************************************************************/

control SwitchDeparser(
    packet_out pkt,
    in header_t hdr) {
    apply {
        pkt.emit(hdr);
    }
}

/*************************************************************************
********************** Checksum Verification *****************************
*************************************************************************/

control SwitchVerifyChecksum(inout header_t hdr,
                       inout metadata_t meta) {
    apply {}
}
/*************************************************************************
********************** Checksum Computation ******************************
*************************************************************************/

control SwitchComputeChecksum(inout header_t hdr,
                        inout metadata_t meta) {
    apply {
        update_checksum(
            hdr.ipv4.isValid(),
            { hdr.ipv4.version,
              hdr.ipv4.ihl,
              hdr.ipv4.diffserv,
              hdr.ipv4.totalLen,
              hdr.ipv4.identification,
              hdr.ipv4.flags,
              hdr.ipv4.fragOffset,
              hdr.ipv4.ttl,
              hdr.ipv4.protocol,
              hdr.ipv4.srcAddr,
              hdr.ipv4.dstAddr },
            hdr.ipv4.hdrChecksum,
            HashAlgorithm.csum16);
        }
}
/*************************************************************************
*********************** Ingress Processing********************************
**************************************************************************/

control SwitchIngress(
    inout header_t hdr,
    inout metadata_t meta,
    inout standard_metadata_t ig_intr_md) {

    action drop() {
        mark_to_drop(ig_intr_md);
    }

    action ipv4_forward(macAddr_t dstAddr, egressSpec_t port) {
            ig_intr_md.egress_spec = port;
            hdr.ethernet.srcAddr = hdr.ethernet.dstAddr;
            hdr.ethernet.dstAddr = dstAddr;
            hdr.ipv4.ttl = hdr.ipv4.ttl - 1;
        }

    table ipv4_lpm {
        key = {
            hdr.ipv4.dstAddr: lpm;
        }
        actions = {
            ipv4_forward;
            drop;
            NoAction;
        }
        size = 1024;
        default_action = drop();
    }

    
    
    
    action write_default_class() {
        meta.result = 1;
    }

    action read_lable(bit<32> label){
        meta.result = label;
    }

    table decision {
        key = { meta.code_f0[0:0]:exact;
                meta.code_f1[1:0]:exact;
                meta.code_f2[2:0]:exact;
                meta.code_f3[2:0]:exact;
                }
        actions={
            read_lable;
            write_default_class;
        }
        size = 13;
        default_action = write_default_class;
    }


    apply{
        if (hdr.ipv4.isValid() && hdr.ipv4.ttl > 0) {
            ipv4_lpm.apply();
        }

        if (hdr.DINC.isValid()) {
            if (hdr.DINC.E_bitmap[2:2] != 1) {
                decision.apply();
            }
            if (hdr.DINC.E_bitmap == 0b11000000000000000000000000000000){
                hdr.DINC_meta.storage0 = meta.result;
            }

        }

    }
}
/*************************************************************************
*********************** egress Processing********************************
**************************************************************************/

control SwitchEgress(inout header_t hdr,
    inout metadata_t meta,
    inout standard_metadata_t eg_intr_md) {
    apply {
    }
}
/*************************************************************************
***********************  S W I T C H  ************************************
*************************************************************************/

V1Switch(
    SwitchParser(),
    SwitchVerifyChecksum(),
    SwitchIngress(),
    SwitchEgress(),
    SwitchComputeChecksum(),
    SwitchDeparser()
) main;